Repository pheature-flags/pheature-flags, pull requests merged in 2021-04, with the labels that each got.

#89 fix missing links in docs
  README.md
  docs/README.md
  docs/architecture/README.md
  docs/getting-started/laminas-and-mezzio-package.md
  docs/getting-started/laravel-package.md
  docs/getting-started/symfony-bundle.md
  docs/packages/dbal-toggle.md
Labels: bug, documentation

#90 add code of conduct on docs
  docs/CODE_OF_CONDUCT.md
Labels: documentation

#91 add temporal og image
  docs/index.html
Labels: documentation

#93 add reviewdog language tool action
  .github/workflows/languaje-tool.yml
Labels: documentation, enhancement

#96 Update README.md
  README.md
Labels: documentation, enhancement

#95 Update Readme.md
  README.md
Labels: bug, documentation

#92 small change in description
  README.md
  docs/README.md
  docs/index.html
Labels: documentation

#100 add wip icon on main readme
  README.md
  docs/README.md
Labels: documentation

#107 point getting started link to docs page
  README.md
Labels: documentation

#101 update contributing repo link
  packages/dbal-toggle/CONTRIBUTING.md
  packages/inmemory-toggle/CONTRIBUTING.md
  packages/laravel-toggle/CONTRIBUTING.md
  packages/mezzio-toggle/CONTRIBUTING.md
  packages/php-sdk/CONTRIBUTING.md
  packages/toggle-core/CONTRIBUTING.md
  packages/toggle-crud-psr11-factories/CONTRIBUTING.md
  packages/toggle-crud-psr7-api/CONTRIBUTING.md
  packages/toggle-crud/CONTRIBUTING.md
  packages/toggle-model/CONTRIBUTING.md
Labels: bug, documentation

#110 test remove github user from split action
  .github/workflows/split_monorepo.yaml
Labels: bug, mvp

#142 add pheaturbot as split commiter
  .github/workflows/split_monorepo.yaml
Labels: bug

#140 [#127] EnableFeatureFactory static
  packages/toggle-crud-psr11-factories/src/EnableFeatureFactory.php
Labels: enhancement, mvp

#136 [#123] AddStrategyFactory static
  packages/toggle-crud-psr11-factories/src/AddStrategyFactory.php
  packages/toggle-crud-psr11-factories/test/AddStrategyFactoryTest.php
Labels: enhancement, mvp

#148 add codecov badge to main package
  .github/workflows/phpunit.yml
  README.md
Labels: documentation

#149 add jetbrains as a first sponsor
  README.md
  docs/README.md
Labels: documentation

#150 add psalm badge
  README.md
  docs/README.md
Labels: documentation

#144 Core model tests
  packages/dbal-toggle/src/Write/DbalFeatureFactory.php
  packages/toggle-core/src/Write/Segment.php
  packages/toggle-core/test/Write/FeatureTest.php
  packages/toggle-core/test/Write/SegmentTest.php
Labels: enhancement, mvp

#155 add code-quality badge
  README.md
Labels: documentation

#158 [#112]: create chain toggle strategy factory
  packages/toggle-core/src/Exception/InvalidStrategyTypeGiven.php
  packages/toggle-core/src/Read/ChainToggleStrategyFactory.php
  packages/toggle-core/src/Read/SegmentFactory.php
  packages/toggle-core/src/Read/Segments.php
  packages/toggle-core/src/Read/WithProcessableFixedTypes.php
  packages/toggle-core/test/Read/ChainToggleStrategyFactoryTest.php
  packages/toggle-core/test/Read/ToggleStrategiesTest.php
Labels: enhancement, mvp

#159 [#113]: create chain segment factory
  packages/toggle-core/src/Exception/InvalidSegmentTypeGiven.php
  packages/toggle-core/src/Read/ChainSegmentFactory.php
  packages/toggle-core/test/Read/ChainSegmentFactoryTest.php
  packages/toggle-core/test/Read/ChainToggleStrategyFactoryTest.php
Labels: enhancement, mvp

#141 [#128] FeatureFinderFactory static
  packages/toggle-crud-psr11-factories/src/FeatureFinderFactory.php
  packages/toggle-crud-psr11-factories/test/FeatureFinderFactoryTest.php
Labels: enhancement, mvp

#139 [#126] DisableFeatureFactory static
  packages/toggle-crud-psr11-factories/src/DisableFeatureFactory.php
  packages/toggle-crud-psr11-factories/test/DisableFeatureFactoryTest.php
Labels: enhancement, mvp

#162 [#129] FeatureRepositoryFactory Static & Test
  packages/toggle-crud-psr11-factories/src/FeatureRepositoryFactory.php
  packages/toggle-crud-psr11-factories/test/FeatureRepositoryFactoryTest.php
Labels: enhancement, mvp

#161 [#115] create segment factory
  packages/toggle-model/src/IdentitySegment.php
  packages/toggle-model/src/Segment.php
  packages/toggle-model/src/SegmentFactory.php
  packages/toggle-model/test/SegmentFactoryTest.php
Labels: enhancement, mvp

#167 [Toggle PSR-11 Factories] Add static version to PostFeatureFactory
  packages/toggle-crud-psr11-factories/src/PostFeatureFactory.php
  packages/toggle-crud-psr11-factories/test/PostFeatureFactoryTest.php
Labels: enhancement, good first issue, mvp

#168 [#117] Rename current Segment to StrictMatchingSegment
  packages/dbal-toggle/src/Read/DbalFeatureFactory.php
  packages/inmemory-toggle/src/InMemoryFeatureFactory.php
  packages/toggle-model/src/SegmentFactory.php
  packages/toggle-model/src/StrictMatchingSegment.php
  packages/toggle-model/test/EnableByMatchingIdentityIdTest.php
  packages/toggle-model/test/EnableByMatchingSegmentTest.php
  packages/toggle-model/test/SegmentFactoryTest.php
Labels: enhancement

#181 [#170] create segment factory compiler pass
  packages/symfony-toggle/src/DependencyInjection/PheatureFlagsExtension.php
  packages/symfony-toggle/src/DependencyInjection/SegmentFactoryPass.php
  packages/symfony-toggle/src/PheatureFlagsBundle.php
  packages/symfony-toggle/test/DependencyInjection/SegmentFactoryPassTest.php
Labels: enhancement, mvp

#184 [#183] add symfony toggle package badges
  README.md
  packages/symfony-toggle/README.md
Labels: documentation

#189 [Symfony Toggle]: send phpunit report to codecov
  packages/symfony-toggle/.github/workflows/phpunit.yml
Labels: bug

#186 [#185] WIP start documenting Symfony toggle
  docs/getting-started/symfony-bundle.md
Labels: documentation, mvp
