Repository pheature-flags/pheature-flags, pull requests merged in 2021-05, with the labels that each got.

#193 [#80] Add psalm type check badge to Toggle CRUD PSR-7 API package
  packages/toggle-crud-psr7-api/README.md
Labels: mvp

#194 [#174] create feature repository compiler pass
  packages/symfony-toggle/composer.json
  packages/symfony-toggle/config/dbal_config.yaml
  packages/symfony-toggle/src/DependencyInjection/FeatureRepositoryFactoryPass.php
  packages/symfony-toggle/src/DependencyInjection/PheatureFlagsExtension.php
  packages/symfony-toggle/src/PheatureFlagsBundle.php
  packages/symfony-toggle/test/DependencyInjection/FeatureRepositoryFactoryPassTest.php
  packages/symfony-toggle/test/DependencyInjection/TestContainerFactory.php
Labels: enhancement, mvp

#198 HOTFIX: load compiler passes from bundle class
  packages/symfony-toggle/src/DependencyInjection/PheatureFlagsExtension.php
  packages/symfony-toggle/src/PheatureFlagsBundle.php
Labels: bug, mvp

#201 [#200] Some fixes creating db schema
  packages/dbal-toggle/composer.json
  packages/dbal-toggle/src/Cli/InitSchema.php
  packages/dbal-toggle/src/Container/InitSchemaFactory.php
  packages/dbal-toggle/src/DbalSchema.php
  packages/dbal-toggle/src/Read/DbalFeatureFactory.php
  packages/dbal-toggle/src/Write/DbalFeatureFactory.php
  packages/dbal-toggle/test/Container/InitSchemaFactoryTest.php
  packages/dbal-toggle/test/DbalSchemaTest.php
Labels: bug, mvp

#207 [#206] install psalm infection plugin
  composer.json
  packages/dbal-toggle/composer.json
  packages/dbal-toggle/src/Read/DbalFeatureFinder.php
  packages/inmemory-toggle/composer.json
  packages/laravel-toggle/composer.json
  packages/mezzio-toggle/composer.json
  packages/php-sdk/composer.json
  packages/symfony-toggle/composer.json
  packages/toggle-core/composer.json
  packages/toggle-crud-psr11-factories/composer.json
  packages/toggle-crud-psr7-api/composer.json
  packages/toggle-crud/composer.json
  packages/toggle-model/composer.json
Labels: enhancement

#214 HOTFIX: add consistency on serializing segment criteria
  packages/dbal-toggle/src/Write/DbalFeatureFactory.php
  packages/dbal-toggle/test/Write/DbalFeatureFactoryTest.php
  packages/toggle-core/src/Write/Segment.php
  packages/toggle-core/test/Write/SegmentTest.php
Labels: bug, mvp

#216 [#215] get commit user in github action
  .github/workflows/split_monorepo.yaml
Labels: bug, mvp

#220 [#219] update chain toggle strategy factory to fit strategy factory contract
  packages/toggle-core/src/Read/ChainToggleStrategyFactory.php
  packages/toggle-core/test/Read/ChainToggleStrategyFactoryTest.php
Labels: enhancement

#228 [#227][pheature-flags] Add Makefile to run a single precommit check
  Makefile
Labels: enhancement, mvp
